<?php

/**
 * @file
 * Contains dummy.module.
 */

use Drupal\Core\Asset\AttachedAssetsInterface;
use Drupal\Core\Language\LanguageInterface;
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function dummy_help($route_name, RouteMatchInterface $route_match) {
  $output = '';

  switch ($route_name) {
    case 'help.page.dummy':
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('This plugin supports an enlisted html classes of SPAN by model to prevent their deletion in CKEditor 5.') . '</p>';
  }
  return $output;
}

/**
 * Implements hook_css_alter().
 */
function dummy_css_alter(&$css, AttachedAssetsInterface $assets, LanguageInterface $language) {

  if (isset($css['core/modules/ckeditor5/css/editor.css'])) {
    $module = 'dummy';
    $module_path = \Drupal::service('extension.list.module')->getPath($module);
    $info = \Drupal::service('extension.list.module')->getExtensionInfo($module);

    if (isset($info['ckeditor5-stylesheets']) && $info['ckeditor5-stylesheets'] !== FALSE) {
      $cssCKE5 = $info['ckeditor5-stylesheets'];

      foreach ($cssCKE5 as $url) {
        $cssUri = $module_path . '/' . $url;
        $css[$cssUri] = [
          'type' => 'file',
          'data' => $cssUri,
          'version' => -1,
          'weight' => 0,
          'media' => 'all',
          'group' => CSS_AGGREGATE_DEFAULT,
          'preprocess' => TRUE,
          'license' => [
            'name' => 'GNU-GPL-2.0-or-later',
            'url' => 'https://www.drupal.org/licensing/faq',
            'gpl-compatible' => TRUE,
          ],
        ];
      }
    }
  }
}
