<?php

/**
 * @file
 * Contains dummy.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function dummy_help($route_name, RouteMatchInterface $route_match) {
  $output = '';

  switch ($route_name) {
    case 'help.page.dummy':
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('This plugin supports an enlisted html classes of SPAN by model to prevent their deletion in CKEditor 5.') . '</p>';
  }
  return $output;
}

