
# Plugin \Drupal\dummy\Plugin\CKEditor5Plugin\dummy
ckeditor5.plugin.dummy_dummy:
  type: mapping
  label: 'Dummy settings'
  mapping:
    classes:
      type: string
      label: 'SPAN HTML classes to support'
    classes_div:
      type: string
      label: 'DIV HTML classes to support'
    classes_ol:
      type: string
      label: 'OL HTML classes to support'
    classes_ul:
      type: string
      label: 'UL HTML classes to support'



